로그인 페이지 작업 완료
KDT3-miniproject-team1/frontend pull request #26
Opened 2023-02-16 09:58 UTC by mineclover

## 작업 개요 (이슈 번호)

Close #20

## 작업 내용 (변경 사항)

- 피그마 기반으로 로그인 페이지 만듬
- 글자스타일을 컴포넌트 모듈로해서- untils/FigmaStyles.tsx 에 만들어두고 사용함
- untils/StyledUntils.tsx 에 만들어두고 사용함

## 스크린샷
![image](https://user-images.githubusercontent.com/61359316/219331241-ce0476e5-9493-41ef-b904-5139b685df77.png)

## 리뷰 요청 사항

2023-02-16 12:17 UTC, yujiseok requested changes

2023-02-16 12:17 UTC, yujiseok commented on src/pages/SignIn.tsx
> +        value: /^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
html 자체적으로 유효성 검증을 진행하실 건가요? 
아니면 추후에 유효성 검증 라이브러리를 사용하실 예정이신가요?

2023-02-16 12:17 UTC, yujiseok commented on src/pages/SignIn.tsx
> +}
객체 하나인데 복수형을 붙일 필요는 없을 것 같습니다. 또한 위에서 언급했다 싶이 `Forms`보다는 input을 나타내는 의미가 있는 키워드로 바꾸면 더 좋을 거 같네요.

2023-02-16 12:17 UTC, yujiseok commented on src/pages/SignIn.tsx
> +  [index: string]: string | FieldError;
이 index는 어디에 쓰이는 걸까요?

2023-02-16 12:17 UTC, yujiseok commented on src/pages/SignIn.tsx
> +        {forms.map(({ label, type, options, Prefix, name }) => (
`forms`로 하는 것 보다 **inputs** 혹은 **textFields** 등 과 같이 좀 더 의미가 확실한 변수로 바꾸는 것이 어떨까요?

2023-02-16 12:17 UTC, yujiseok commented on src/components/auth/InputModule.tsx
> +  register: any;
any로 지정하는 것 보다는 

```ts
register: {
    onChange: (e: ChangeEvent<HTMLInputElement>) => void;
    onBlur: (e: FocusEvent<HTMLInputElement>) => void;
    ref: RefCallback<HTMLInputElement>;
    name: string;
    min?: string | number;
    max?: string | number;
    maxLength?: number;
    minLength?: number;
    pattern?: string;
    required?: boolean;
    disabled?: boolean;
  }
  
  ```
  
  이런식으로 하는 것은 어떨까요?

2023-02-16 12:49 UTC, mineclover commented on src/components/untils/FigmaStyles.tsx
> +import styled from "styled-components";
피그마에 디폴트로 있는 거 모아뒀습니다

2023-02-16 12:50 UTC, mineclover commented on src/components/untils/FigmaStyles.tsx
> +export const Pretendard = styled.div`
피그마 폰트 스타일에 선언된 스타일입니다
색 입력으로 바뀌게 해둔거에요

2023-02-16 12:50 UTC, mineclover commented on src/pages/SignIn.tsx
> +        value: /^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
해당 코드에서 검증도 됩니다

2023-02-16 12:51 UTC, mineclover commented on src/pages/SignIn.tsx
> +}
Forms 는 객체 배열로 사용됩니다
```
  const forms: Forms[] = [
    {
```

2023-02-16 12:55 UTC, mineclover commented on src/components/untils/StyledUntils.tsx
> +import styled from "styled-components";
로그인 ~ 회원가입에서 공통적으로 쓰인 것 모아놨습니다

2023-02-16 13:15 UTC, mineclover commented on src/components/auth/InputModule.tsx
> +  register: any;
쓸 당시에 잘 몰라서 저렇게 해놨는데
라이브러리에서 가져올 수 있는 UseFormRegister 타입이 적용됩니다

2023-02-16 14:56 UTC, mineclover commented on src/pages/SignIn.tsx
> +        {forms.map(({ label, type, options, Prefix, name }) => (
수정했습니다

2023-02-16 18:13 UTC, mineclover commented on src/components/auth/InputModule.tsx
> +  register: any;
options에는 RegisterOptions 이 적용되네요

2023-02-17 04:15 UTC, yujiseok commented on src/pages/SignIn.tsx
> +  [index: string]: string | FieldError;
레코드 타입을 사용해도 좋을 거 같네요

2023-02-17 04:16 UTC, yujiseok commented on src/components/untils/StyledUntils.tsx
> +import styled from "styled-components";
로그인 ~ 회원가입에서 쓰이는 거면 유틸로 빼기보단 그냥 그 파일에서 관리하는 게 좋아 보입니다

2023-02-17 04:17 UTC, yujiseok commented on src/pages/SignIn.tsx
> +        value: /^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
zod 안쓰신다는 말이죠?

2023-02-17 04:17 UTC, yujiseok commented on src/components/auth/InputModule.tsx
> +  register: any;
네 저는 저렇게 해야 되어서 해결 해결 되어서 다행이네요~

2023-02-17 04:20 UTC, yujiseok commented on src/components/untils/StyledUntils.tsx
> +import styled from "styled-components";
untils가 utils인가요?

2023-02-17 04:20 UTC, yujiseok commented on src/components/untils/FigmaStyles.tsx
> +import styled from "styled-components";
폰트는 나중에 같이 쓸 수 도 있으니까 글로벌로 옮기는게 어떨까요

2023-02-17 04:50 UTC, mineclover commented on src/pages/SignIn.tsx
> +        value: /^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
넹

2023-02-17 05:00 UTC, mineclover commented on src/pages/SignIn.tsx
> +  [index: string]: string | FieldError;
오 좋네요

2023-02-17 06:10 UTC, mineclover commented on src/components/untils/StyledUntils.tsx
> +import styled from "styled-components";
그렇네요

2023-02-17 06:11 UTC, mineclover commented on src/components/untils/FigmaStyles.tsx
> +import styled from "styled-components";
옮겼습니당

2023-02-17 06:13 UTC, yujiseok approved these changes

2023-02-17 06:13 UTC, merged