Feature/park jeong min
KDT3-miniproject-team1/frontend pull request #27
Opened 2023-02-16 12:48 UTC by plou102

## 작업 개요 (이슈 번호)

Close #7 
Close #22 

## 작업 내용 (변경 사항)
- 헤더 초기값 문자열로 변경
- 입력창을 감싸고 있는 div form으로 변경
- 헤더 푸터 고정 및 layout -> main 스타일 변경 (헤더를 고정하는 과정에서 헤더와 메인컨텐츠가 겹쳐서 패딩 값을 변경하였습니다.)
- 메인 ui
- 리스트 구조를 보기 위해 더미 데이터를 생성하였습니다.
- 로그인 / 회원가입 버튼 페이지 이동
- 추천 상품 클릭시 상세 페이지로 이동

## 스크린샷

https://user-images.githubusercontent.com/107393773/219367141-d61e828e-b5e1-4305-aa3c-f12d212e8239.mov

## 리뷰 요청 사항
- 헤더에서 검색을 하면 주소가 /search/헬로?search= 이렇게 가는데 ?search를 어떻게 빼야 할지 모르겠습니다. 😭

2023-02-16 14:04 UTC, zwonkim commented
form으ㅣ method가 get 방식이어서 데이터값이 url에 붙어서 전송되는 거 아닐까요..? 혹시 method를 post로 변경해보셨나욥??

2023-02-17 03:54 UTC, plou102 commented
post로 해보려고 했는데 제가 이상하게 한건지 오류가 나서염....ㅠㅠ

2023-02-17 04:38 UTC, yujiseok requested changes
아 그 인풋창 트랜지션을 좀만 빠르게 하는 건 어떨까요?
그리고 아이콘은 그거로 고정인가요?!

2023-02-17 04:38 UTC, yujiseok commented on src/components/Header.tsx
> +          }}
```ts
onSubmit={submitEvent}
```

이렇게 하고 `e.preventDefault()` 넣어도 안없어지나요?

2023-02-17 04:38 UTC, yujiseok commented on src/pages/Main.tsx
> +          로그인
navigate 사용을 해도 되는데, Link를 이용해서 하는 건 어떨까요?! 

어차피 클릭시 바로 이동하는 로직이라..!

2023-02-17 04:38 UTC, yujiseok commented on src/data/listData.json
> +{
안그래도 더미 데이터 있으면 좋겠다 생각하고 있었는데!
감사합니다 ❗

2023-02-17 04:46 UTC, plou102 commented on src/pages/Main.tsx
> +          로그인
적용해 보겠습니다~~

2023-02-17 04:51 UTC, plou102 commented on src/components/Header.tsx
> +          }}
오오오 찾았어요!! 저렇게 하니까 되네염 👍👍
감사합니다~~

2023-02-17 05:04 UTC, plou102 commented on src/data/listData.json
> +{
검색 아이콘은 저거로 고정할 것 같습니다~~

2023-02-17 05:13 UTC, yujiseok approved these changes

2023-02-17 05:14 UTC, merged