회원 가입 페이지 추가
KDT3-miniproject-team1/frontend pull request #40
Opened 2023-02-17 18:39 UTC by mineclover

## 작업 개요 (이슈 번호)

Close #39

## 작업 내용 (변경 사항)

- 화면이 길어지는데 App이 height 100vh 이여서 수정

## 스크린샷

![localhost_3000_signup](https://user-images.githubusercontent.com/61359316/219751777-587c3ed4-e3da-40f3-bc20-4730d1d05be0.png)

## 리뷰 요청 사항

2023-02-20 06:03 UTC, yujiseok requested changes

2023-02-20 06:03 UTC, yujiseok commented on src/pages/SingUp.tsx
> +  const b = Object.keys(errors).length;
a,b의 역할이 무엇일까요

2023-02-20 06:37 UTC, mineclover commented on src/pages/SingUp.tsx
> +  }, []);
초기 렌더링에 유효성검사 바로 실행시키는 목적입니다

2023-02-20 06:41 UTC, yujiseok commented on src/pages/SingUp.tsx
> +  }, []);
그러면 저 화면에 들어가자마자 에러 메시지가 보이는 건가요?

2023-02-20 06:49 UTC, mineclover commented on src/pages/SingUp.tsx
> +  }, []);
넹

2023-02-20 06:49 UTC, mineclover commented on src/components/auth/CheckBoxButton.tsx
> +  font-family: "Pretendard";
수정했습니다

2023-02-20 06:49 UTC, mineclover commented on src/pages/SingUp.tsx
> +  const b = Object.keys(errors).length;
수정했습니다

2023-02-20 06:57 UTC, yujiseok commented on src/pages/SingUp.tsx
> +  }, []);
흠 플레이스홀더로 보여주면 되지않을까요?

2023-02-20 07:14 UTC, mineclover commented on src/pages/SingUp.tsx
> +  }, []);
리액트 훅스 폼의 유효성검사가 handleSubmit가 한번 실행된 이후 실행되서 
회원가입 옆에 진행 상황 체크하는 걸 추가하려면 초기에 handleSubmit를 실행해야합니다

2023-02-20 07:25 UTC, mineclover commented on src/pages/SingUp.tsx
> +  }, []);
그런데 이거 trigger(); 로도 대체되긴 하네요 이걸로 수정했습니다

2023-02-20 08:00 UTC, yujiseok commented on src/pages/SingUp.tsx
> +  }, []);
정확히 어떻게 보이는지 보고 싶은데요
gif라든지 없나요
초기에 화면 진입하자마자 빨간색으로 에러 메시지가 보이면 별로일 거 같아서요

2023-02-20 08:05 UTC, mineclover commented on src/pages/SingUp.tsx
> +  }, []);
확인해보니까 trigger는 변경 반영이 안되네요
handleSubmit 쓰는게 맞네요
![없앰](https://user-images.githubusercontent.com/61359316/220047485-a359c457-8c8d-4a09-8f55-c0793962d6fb.gif)
![handleSubmit](https://user-images.githubusercontent.com/61359316/220047495-4b1086cc-7014-41e8-a4a6-0da8fd0f9fcc.gif)

2023-02-21 04:07 UTC, yujiseok approved these changes

2023-02-21 04:07 UTC, merged