Feat: 장바구니 헤더 추가
KDT3-miniproject-team1/frontend pull request #50
Opened 2023-02-20 08:04 UTC by zwonkim

## 작업 개요 (이슈 번호)

Close #

## 작업 내용 (변경 사항)
- 장바구니 페이지 헤더 작업(CartHeader 컴포넌트 생성)
- CartItem 컴포넌트 삭제 후 ItemList 컴포넌트 재사용
- ItemList 스타일링 수정 및 아이콘 링크 태그 수정

## 스크린샷
<img width="425" alt="스크린샷 2023-02-20 오후 5 01 42" src="https://user-images.githubusercontent.com/103507999/220047428-b99f09cd-90e8-4121-a7f9-e55308ce3a8a.png">

## 리뷰 요청 사항

2023-02-20 09:41 UTC, yujiseok requested changes

2023-02-20 09:41 UTC, yujiseok commented on src/pages/CompleteOrder.tsx
> +  }
무작위로 셔플을 하는거면 이런식으로도 할 수 있을 것 같아요
```ts
const shuffle = (array) => {
  return [...array].sort(() => Math.random() - 0.5);
};
const result = shuffle(numbers);
```

랜덤 아이디가 필요하면 cryprto 라는 웹api를 사용해도 될 거 같아요
```ts
import crypto from "crypto";

const randomId = crypto.randomUUID()
```

2023-02-20 09:41 UTC, yujiseok commented on src/pages/CompleteOrder.tsx
> +  const orderDate = `${year}.${month}.${day}`;
신청날짜도 `toLocaleDateString` 메서드를 사용하면 좀 더 간편하게 구할 수 있을 거 같아요 ㅎㅎ
```ts
new Date().toLocaleDateString()
```

2023-02-21 06:18 UTC, zwonkim commented on src/pages/CompleteOrder.tsx
> +  }
헉 단순하게 숫자만 뽑아도 될 것 같아서 웹 api는 생각을 안 했는데 shuffle 함수로 완전 짧게 랜덤 번호를 뽑을 수 있었네요 .. 감사합니다 ㅎㅎ 수정ㅎㄹ게욥!

2023-02-21 06:25 UTC, zwonkim commented on src/pages/CompleteOrder.tsx
> +  const orderDate = `${year}.${month}.${day}`;
헐 저거 까먹고 있었어요 .. 대박 ! 지금 바로 수정했어욥 감사합니다 ~

2023-02-21 06:27 UTC, yujiseok approved these changes

2023-02-21 06:27 UTC, merged