Feature/kimjiwon
KDT3-miniproject-team1/frontend pull request #67
Opened 2023-02-22 12:38 UTC by zwonkim

## 작업 개요 (이슈 번호)

Close #66

## 작업 내용 (변경 사항)
백엔드에 토큰 만료기한을 늘려달라고 요청해서 기한이 10분으로 늘어났습니다
장바구니 api가 잘 동작하는지 확인해봤고 itemList의 데이터 이름들을 바꿨습니다

## 스크린샷

## 리뷰 요청 사항
저희 api는 파일을 나눌 예정인가요 ..? 일단은 기존 api에서 장바구니 api를 불러오긴 했는데
기능별로 api 분류할 예정이면 다시 수정해서 푸시할게욥

2023-02-22 12:40 UTC, yujiseok commented
지원님 저희 api 폴더안에 기능별로 api 파일 만들기로 했어요!

2023-02-22 13:02 UTC, yujiseok requested changes

2023-02-23 01:45 UTC, zwonkim commented on src/api/api.ts
> +  const response = await client.get("/cart");
수정완 ~

2023-02-23 04:24 UTC, mineclover requested changes

2023-02-23 04:24 UTC, mineclover commented on src/api/carts.ts
> +const accessToken = "";
let으로 바꿔야할거같네영

2023-02-23 04:25 UTC, yujiseok approved these changes

2023-02-23 04:27 UTC, yujiseok approved these changes

2023-02-23 04:29 UTC, mineclover approved these changes

2023-02-23 04:30 UTC, merged